/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.modulos;

import controlador.Controlador;

/**
 *
 * @author Adonay
 */
public class DialogCuentasLibroDiario extends javax.swing.JDialog {

    /**
     * Creates new form dialogReporteLibroDiario
     */
    public DialogCuentasLibroDiario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void setControlador(Controlador control){
        this.tablaCuentasLibroDiario.addMouseListener(control);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollPanelReporteLibroDiario = new javax.swing.JScrollPane();
        tablaCuentasLibroDiario = new RSMaterialComponent.RSTableMetro();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar cuenta");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ScrollPanelReporteLibroDiario.setBorder(null);

        tablaCuentasLibroDiario.setForeground(new java.awt.Color(255, 255, 255));
        tablaCuentasLibroDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cuenta", "Agregar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentasLibroDiario.setBackgoundHead(new java.awt.Color(240, 240, 240));
        tablaCuentasLibroDiario.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tablaCuentasLibroDiario.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tablaCuentasLibroDiario.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tablaCuentasLibroDiario.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tablaCuentasLibroDiario.setColorSecondary(new java.awt.Color(240, 240, 240));
        tablaCuentasLibroDiario.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tablaCuentasLibroDiario.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tablaCuentasLibroDiario.setFontHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaCuentasLibroDiario.setFontRowSelect(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tablaCuentasLibroDiario.setForegroundHead(new java.awt.Color(51, 51, 51));
        tablaCuentasLibroDiario.setGridColor(new java.awt.Color(255, 255, 255));
        tablaCuentasLibroDiario.setModelSelection(null);
        tablaCuentasLibroDiario.setSelectionBackground(new java.awt.Color(153, 204, 255));
        ScrollPanelReporteLibroDiario.setViewportView(tablaCuentasLibroDiario);
        if (tablaCuentasLibroDiario.getColumnModel().getColumnCount() > 0) {
            tablaCuentasLibroDiario.getColumnModel().getColumn(0).setResizable(false);
            tablaCuentasLibroDiario.getColumnModel().getColumn(1).setResizable(false);
            tablaCuentasLibroDiario.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaCuentasLibroDiario.getColumnModel().getColumn(2).setResizable(false);
        }

        rSTextFieldMaterial1.setForeground(new java.awt.Color(51, 51, 51));
        rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(51, 153, 255));
        rSTextFieldMaterial1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSTextFieldMaterial1.setPhColor(new java.awt.Color(153, 153, 153));
        rSTextFieldMaterial1.setPlaceholder("Buscar cuenta por (código, nombre)");
        rSTextFieldMaterial1.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        rSTextFieldMaterial1.setSelectionColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ScrollPanelReporteLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanelReporteLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogReporteLibroDiario dialog = new DialogReporteLibroDiario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane ScrollPanelReporteLibroDiario;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    public RSMaterialComponent.RSTableMetro tablaCuentasLibroDiario;
    // End of variables declaration//GEN-END:variables
}
