/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.modulos;

import javax.swing.WindowConstants;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Adonay
 */
public class DialogReporteLibroDiario extends javax.swing.JDialog {

    /**
     * Creates new form dialogReporteLibroDiario
     */
    public DialogReporteLibroDiario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollPanelReporteLibroDiario = new javax.swing.JScrollPane();
        tblBaul = new RSMaterialComponent.RSTableMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarPartida = new newscomponents.RSButtonIcon_new();
        btnRegistrarPartida1 = new newscomponents.RSButtonIcon_new();
        btnRegistrarPartida2 = new newscomponents.RSButtonIcon_new();
        btnRegistrarPartida3 = new newscomponents.RSButtonIcon_new();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblBaul.setBackground(new java.awt.Color(255, 255, 255));
        tblBaul.setForeground(new java.awt.Color(255, 255, 255));
        tblBaul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBaul.setBackgoundHead(new java.awt.Color(240, 240, 240));
        tblBaul.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tblBaul.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tblBaul.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tblBaul.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tblBaul.setColorSecondary(new java.awt.Color(240, 240, 240));
        tblBaul.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tblBaul.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblBaul.setFontHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblBaul.setForegroundHead(new java.awt.Color(51, 51, 51));
        tblBaul.setModelSelection(null);
        tblBaul.setSelectionBackground(new java.awt.Color(204, 204, 204));
        ScrollPanelReporteLibroDiario.setViewportView(tblBaul);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("N° de Partida: 1");
        jLabel4.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("San Vicente S. A. de C. V.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Libro diario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Periodo 2022");

        btnRegistrarPartida.setBackground(new java.awt.Color(255, 102, 51));
        btnRegistrarPartida.setText("Imprimir partida actual");
        btnRegistrarPartida.setBackgroundHover(new java.awt.Color(253, 127, 84));
        btnRegistrarPartida.setFocusPainted(false);
        btnRegistrarPartida.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PRINT);
        btnRegistrarPartida.setRound(5);
        btnRegistrarPartida.setSizeIcon(22.0F);
        btnRegistrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartidaActionPerformed(evt);
            }
        });

        btnRegistrarPartida1.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarPartida1.setText("Imprimir Libro Diario");
        btnRegistrarPartida1.setBackgroundHover(new java.awt.Color(130, 171, 255));
        btnRegistrarPartida1.setFocusPainted(false);
        btnRegistrarPartida1.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarPartida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarPartida1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PRINT);
        btnRegistrarPartida1.setRound(5);
        btnRegistrarPartida1.setSizeIcon(22.0F);
        btnRegistrarPartida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartida1ActionPerformed(evt);
            }
        });

        btnRegistrarPartida2.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrarPartida2.setBackgroundHover(new java.awt.Color(130, 171, 255));
        btnRegistrarPartida2.setFocusPainted(false);
        btnRegistrarPartida2.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarPartida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarPartida2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnRegistrarPartida2.setInheritsPopupMenu(true);
        btnRegistrarPartida2.setRound(5);
        btnRegistrarPartida2.setSizeIcon(22.0F);
        btnRegistrarPartida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartida2ActionPerformed(evt);
            }
        });

        btnRegistrarPartida3.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrarPartida3.setBackgroundHover(new java.awt.Color(130, 171, 255));
        btnRegistrarPartida3.setFocusPainted(false);
        btnRegistrarPartida3.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarPartida3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarPartida3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_FORWARD);
        btnRegistrarPartida3.setInheritsPopupMenu(true);
        btnRegistrarPartida3.setRound(5);
        btnRegistrarPartida3.setSizeIcon(22.0F);
        btnRegistrarPartida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartida3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPanelReporteLibroDiario, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarPartida2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPartida3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanelReporteLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarPartida2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarPartida3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartidaActionPerformed

    }//GEN-LAST:event_btnRegistrarPartidaActionPerformed

    private void btnRegistrarPartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPartida1ActionPerformed

    private void btnRegistrarPartida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPartida2ActionPerformed

    private void btnRegistrarPartida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartida3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPartida3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogReporteLibroDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogReporteLibroDiario dialog = new DialogReporteLibroDiario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane ScrollPanelReporteLibroDiario;
    public newscomponents.RSButtonIcon_new btnRegistrarPartida;
    public newscomponents.RSButtonIcon_new btnRegistrarPartida1;
    public newscomponents.RSButtonIcon_new btnRegistrarPartida2;
    public newscomponents.RSButtonIcon_new btnRegistrarPartida3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static RSMaterialComponent.RSTableMetro tblBaul;
    // End of variables declaration//GEN-END:variables
}
