/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.modulos;

import controlador.Controlador;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Adonay
 */
public class PnlLibroDiario extends javax.swing.JPanel {

    /**
     * Creates new form pnlListDisks
     */
    public PnlLibroDiario() {
        initComponents();
        this.btnRegistrarPartida.setActionCommand("btnRegistrarPartida");
        this.btnReportePartidas.setActionCommand("btnReportePartidas");
        this.btnVolverLibroDiario.setActionCommand("btnVolverLibroDiario");
        this.btnBuscarCuentaPartida.setActionCommand("btnBuscarCuentaPartida");
    }
    
    public void setControlador(Controlador control){
        this.btnRegistrarPartida.addActionListener(control);
        this.btnReportePartidas.addActionListener(control);
        this.btnVolverLibroDiario.addActionListener(control);
        this.btnBuscarCuentaPartida.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        btnVolverLibroDiario = new newscomponents.RSButtonIcon_new();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBaul = new RSMaterialComponent.RSTableMetro();
        btnRegistrarPartida = new newscomponents.RSButtonIcon_new();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSDateChooserModern1 = new newscomponents.RSDateChooserModern();
        jLabel3 = new javax.swing.JLabel();
        rSTextFieldOne1 = new RSMaterialComponent.RSTextFieldOne();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarCuentaPartida = new newscomponents.RSButtonIcon_new();
        rSTextFieldOne2 = new RSMaterialComponent.RSTextFieldOne();
        rSTextFieldOne3 = new RSMaterialComponent.RSTextFieldOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSTextFieldOne4 = new RSMaterialComponent.RSTextFieldOne();
        jLabel8 = new javax.swing.JLabel();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarCuentaPartida = new newscomponents.RSButtonIcon_new();
        jLabel5 = new javax.swing.JLabel();
        btnReportePartidas = new newscomponents.RSButtonIcon_new();

        setBackground(new java.awt.Color(255, 255, 255));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(0, 102, 255));
        rSPanelBorder1.setBorderLeft(false);
        rSPanelBorder1.setBorderRight(false);
        rSPanelBorder1.setBorderTop(false);

        rSLabelTextIcon1.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Libro diario / Registrar partida");
        rSLabelTextIcon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        rSLabelTextIcon1.setSizeIcon(30.0F);

        btnClose.setBackground(new java.awt.Color(0, 102, 255));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.setRound(5);
        btnClose.setSizeIcon(30.0F);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        btnVolverLibroDiario.setBackground(new java.awt.Color(102, 102, 102));
        btnVolverLibroDiario.setText("Volver");
        btnVolverLibroDiario.setBackgroundHover(new java.awt.Color(121, 121, 121));
        btnVolverLibroDiario.setFocusPainted(false);
        btnVolverLibroDiario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVolverLibroDiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverLibroDiario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnVolverLibroDiario.setRound(5);
        btnVolverLibroDiario.setSizeIcon(22.0F);
        btnVolverLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLibroDiarioActionPerformed(evt);
            }
        });

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setShapePanel(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblBaul.setForeground(new java.awt.Color(255, 255, 255));
        tblBaul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBaul.setBackgoundHead(new java.awt.Color(240, 240, 240));
        tblBaul.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tblBaul.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tblBaul.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tblBaul.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tblBaul.setColorSecondary(new java.awt.Color(240, 240, 240));
        tblBaul.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tblBaul.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblBaul.setFontHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblBaul.setForegroundHead(new java.awt.Color(51, 51, 51));
        tblBaul.setModelSelection(null);
        tblBaul.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tblBaul);
        if (tblBaul.getColumnModel().getColumnCount() > 0) {
            tblBaul.getColumnModel().getColumn(0).setResizable(false);
            tblBaul.getColumnModel().getColumn(1).setResizable(false);
            tblBaul.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblBaul.getColumnModel().getColumn(2).setResizable(false);
            tblBaul.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRegistrarPartida.setBackground(new java.awt.Color(27, 172, 27));
        btnRegistrarPartida.setText("Registrar transacción");
        btnRegistrarPartida.setBackgroundHover(new java.awt.Color(30, 191, 30));
        btnRegistrarPartida.setFocusPainted(false);
        btnRegistrarPartida.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnRegistrarPartida.setRound(5);
        btnRegistrarPartida.setSizeIcon(22.0F);
        btnRegistrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("0.00");

        rSDateChooserModern1.setBackground(new java.awt.Color(102, 102, 102));
        rSDateChooserModern1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSDateChooserModern1.setFormatDate("dd/MM/yyyy");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Código");

        rSTextFieldOne1.setForeground(new java.awt.Color(51, 51, 51));
        rSTextFieldOne1.setBorderColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSTextFieldOne1.setPhColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne1.setPlaceholder("Digite una descripción");
        rSTextFieldOne1.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descripción");

        btnBuscarCuentaPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarCuentaPartida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 170, 227)));
        btnBuscarCuentaPartida.setForeground(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setText("Buscar cuenta");
        btnBuscarCuentaPartida.setBackgroundHover(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setFocusPainted(false);
        btnBuscarCuentaPartida.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnBuscarCuentaPartida.setForegroundIcon(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setForegroundText(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCuentaPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarCuentaPartida.setRound(5);
        btnBuscarCuentaPartida.setSizeIcon(22.0F);
        btnBuscarCuentaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaPartidaActionPerformed(evt);
            }
        });

        rSTextFieldOne2.setForeground(new java.awt.Color(51, 51, 51));
        rSTextFieldOne2.setBorderColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne2.setEnabled(false);
        rSTextFieldOne2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSTextFieldOne2.setPhColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne2.setPlaceholder("-");
        rSTextFieldOne2.setSelectionColor(new java.awt.Color(204, 204, 204));

        rSTextFieldOne3.setForeground(new java.awt.Color(51, 51, 51));
        rSTextFieldOne3.setBorderColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne3.setEnabled(false);
        rSTextFieldOne3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSTextFieldOne3.setPhColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne3.setPlaceholder("-");
        rSTextFieldOne3.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre de cuenta");

        rSTextFieldOne4.setForeground(new java.awt.Color(51, 51, 51));
        rSTextFieldOne4.setBorderColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSTextFieldOne4.setPhColor(new java.awt.Color(102, 102, 102));
        rSTextFieldOne4.setPlaceholder("0.00");
        rSTextFieldOne4.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Saldo ($)");

        rSComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        rSComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Deudor", "Acreedor" }));
        rSComboBox1.setColorArrow(new java.awt.Color(51, 51, 51));
        rSComboBox1.setColorBorde(new java.awt.Color(102, 102, 102));
        rSComboBox1.setColorFondo(new java.awt.Color(255, 255, 255));
        rSComboBox1.setColorListaItemsTXT(new java.awt.Color(51, 51, 51));
        rSComboBox1.setColorSeleccion(new java.awt.Color(204, 204, 204));
        rSComboBox1.setColorSeleccionTXT(new java.awt.Color(51, 51, 51));
        rSComboBox1.setConBorde(true);
        rSComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tipo de saldo");

        btnAgregarCuentaPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCuentaPartida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 172, 27)));
        btnAgregarCuentaPartida.setForeground(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setText("Agregar cuenta");
        btnAgregarCuentaPartida.setBackgroundHover(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setFocusPainted(false);
        btnAgregarCuentaPartida.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAgregarCuentaPartida.setForegroundIcon(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setForegroundText(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarCuentaPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAgregarCuentaPartida.setRound(5);
        btnAgregarCuentaPartida.setSizeIcon(22.0F);
        btnAgregarCuentaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSTextFieldOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(332, 489, Short.MAX_VALUE))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(rSComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSDateChooserModern1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(rSTextFieldOne1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(btnBuscarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSTextFieldOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSTextFieldOne3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSTextFieldOne1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(rSDateChooserModern1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSTextFieldOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("N° de Partida: 1");

        btnReportePartidas.setBackground(new java.awt.Color(249, 158, 9));
        btnReportePartidas.setText("Reporte de partidas");
        btnReportePartidas.setBackgroundHover(new java.awt.Color(249, 180, 66));
        btnReportePartidas.setFocusPainted(false);
        btnReportePartidas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnReportePartidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportePartidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER);
        btnReportePartidas.setRound(5);
        btnReportePartidas.setSizeIcon(22.0F);
        btnReportePartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePartidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(btnVolverLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportePartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolverLibroDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportePartidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCuentaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaPartidaActionPerformed

    }//GEN-LAST:event_btnAgregarCuentaPartidaActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        RSUtilities.setClosed();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnVolverLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLibroDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverLibroDiarioActionPerformed

    private void btnBuscarCuentaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCuentaPartidaActionPerformed

    private void btnRegistrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartidaActionPerformed

    }//GEN-LAST:event_btnRegistrarPartidaActionPerformed

    private void btnReportePartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePartidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePartidasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonIcon_new btnAgregarCuentaPartida;
    public newscomponents.RSButtonIcon_new btnBuscarCuentaPartida;
    private RSMaterialComponent.RSButtonIconOne btnClose;
    public newscomponents.RSButtonIcon_new btnRegistrarPartida;
    public newscomponents.RSButtonIcon_new btnReportePartidas;
    public newscomponents.RSButtonIcon_new btnVolverLibroDiario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private newscomponents.RSDateChooserModern rSDateChooserModern1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSTextFieldOne rSTextFieldOne1;
    private RSMaterialComponent.RSTextFieldOne rSTextFieldOne2;
    private RSMaterialComponent.RSTextFieldOne rSTextFieldOne3;
    private RSMaterialComponent.RSTextFieldOne rSTextFieldOne4;
    public static RSMaterialComponent.RSTableMetro tblBaul;
    // End of variables declaration//GEN-END:variables
}
