/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.modulos;

import controlador.Controlador;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Adonay
 */
public class PnlLibros extends javax.swing.JPanel {

    /**
     * Creates new form pnlAbout
     */
    public PnlLibros() {
        initComponents();
        this.btnLibroDiario.setActionCommand("btnLibroDiario");
        this.btnLibroMayor.setActionCommand("btnLibroMayor");
    }
    
    public void setControlador(Controlador control){
        this.btnLibroDiario.addActionListener(control);
        this.btnLibroMayor.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        btnLibroDiario = new RSMaterialComponent.RSButtonMaterialOne();
        btnLibroMayor = new RSMaterialComponent.RSButtonMaterialOne();
        labelCantidadCuentasUtilizadas = new javax.swing.JLabel();
        labelCantidadPartidas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(0, 102, 255));
        rSPanelBorder1.setBorderLeft(false);
        rSPanelBorder1.setBorderRight(false);
        rSPanelBorder1.setBorderTop(false);

        rSLabelTextIcon1.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Seleccione el libro");
        rSLabelTextIcon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        rSLabelTextIcon1.setSizeIcon(30.0F);

        btnClose.setBackground(new java.awt.Color(0, 102, 255));
        btnClose.setBackgroundHover(new java.awt.Color(0, 153, 255));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.setRound(5);
        btnClose.setSizeIcon(30.0F);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnLibroDiario.setBackground(new java.awt.Color(255, 28, 28));
        btnLibroDiario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));
        btnLibroDiario.setText("Libro Diario");
        btnLibroDiario.setBackgroundHover(new java.awt.Color(193, 20, 20));
        btnLibroDiario.setDefaultCapable(false);
        btnLibroDiario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLibroDiario.setRound(5);
        btnLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroDiarioActionPerformed(evt);
            }
        });

        btnLibroMayor.setBackground(new java.awt.Color(0, 102, 255));
        btnLibroMayor.setText("Libro Mayor");
        btnLibroMayor.setBackgroundHover(new java.awt.Color(0, 153, 255));
        btnLibroMayor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLibroMayor.setRound(5);
        btnLibroMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroMayorActionPerformed(evt);
            }
        });

        labelCantidadCuentasUtilizadas.setBackground(new java.awt.Color(54, 134, 255));
        labelCantidadCuentasUtilizadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCantidadCuentasUtilizadas.setForeground(new java.awt.Color(255, 255, 255));
        labelCantidadCuentasUtilizadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidadCuentasUtilizadas.setText("N° de Cuentas utilizadas: 10");
        labelCantidadCuentasUtilizadas.setOpaque(true);

        labelCantidadPartidas.setBackground(new java.awt.Color(255, 58, 58));
        labelCantidadPartidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCantidadPartidas.setForeground(new java.awt.Color(255, 255, 255));
        labelCantidadPartidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidadPartidas.setText("N° de Partidas: 10");
        labelCantidadPartidas.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLibroDiario, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(labelCantidadPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLibroMayor, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(labelCantidadCuentasUtilizadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLibroMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidadPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCantidadCuentasUtilizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(380, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroDiarioActionPerformed
        
    }//GEN-LAST:event_btnLibroDiarioActionPerformed

    private void btnLibroMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroMayorActionPerformed
       
    }//GEN-LAST:event_btnLibroMayorActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        RSUtilities.setClosed();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnClose;
    private RSMaterialComponent.RSButtonMaterialOne btnLibroDiario;
    private RSMaterialComponent.RSButtonMaterialOne btnLibroMayor;
    private javax.swing.JLabel labelCantidadCuentasUtilizadas;
    public javax.swing.JLabel labelCantidadPartidas;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    // End of variables declaration//GEN-END:variables
}
