/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.modulos;

import controlador.Controlador;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Adonay
 */
public class PnlLibroDiario extends javax.swing.JPanel {

    /**
     * Creates new form pnlListDisks
     */
    public PnlLibroDiario() {
        initComponents();
        this.btnRegistrarTransaccion.setActionCommand("btnRegistrarPartida");
        this.btnReportePartidas.setActionCommand("btnReportePartidas");
        this.btnVolverLibroDiario.setActionCommand("btnVolverLibroDiario");
        this.btnBuscarCuentaPartida.setActionCommand("btnBuscarCuentaPartida");
        this.btnAgregarCuentaPartida.setActionCommand("btnAgregarCuentaPartida");
    }
    
    public void setControlador(Controlador control){
        this.btnRegistrarTransaccion.addActionListener(control);
        this.btnReportePartidas.addActionListener(control);
        this.btnVolverLibroDiario.addActionListener(control);
        this.btnBuscarCuentaPartida.addActionListener(control);
        this.btnAgregarCuentaPartida.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        btnVolverLibroDiario = new newscomponents.RSButtonIcon_new();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCuentaTransaccion = new RSMaterialComponent.RSTableMetro();
        btnRegistrarTransaccion = new newscomponents.RSButtonIcon_new();
        labelDebe = new javax.swing.JLabel();
        labelHaber = new javax.swing.JLabel();
        inputFecha = new newscomponents.RSDateChooserModern();
        jLabel3 = new javax.swing.JLabel();
        inputConcepto = new RSMaterialComponent.RSTextFieldOne();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarCuentaPartida = new newscomponents.RSButtonIcon_new();
        inputCodigoCuenta = new RSMaterialComponent.RSTextFieldOne();
        inputNomCuenta = new RSMaterialComponent.RSTextFieldOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputSaldo = new RSMaterialComponent.RSTextFieldOne();
        jLabel8 = new javax.swing.JLabel();
        selectTipoSaldo = new RSMaterialComponent.RSComboBox();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarCuentaPartida = new newscomponents.RSButtonIcon_new();
        jLabel5 = new javax.swing.JLabel();
        btnReportePartidas = new newscomponents.RSButtonIcon_new();

        setBackground(new java.awt.Color(255, 255, 255));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(0, 102, 255));
        rSPanelBorder1.setBorderLeft(false);
        rSPanelBorder1.setBorderRight(false);
        rSPanelBorder1.setBorderTop(false);

        rSLabelTextIcon1.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Libro diario / Registrar partida");
        rSLabelTextIcon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        rSLabelTextIcon1.setSizeIcon(30.0F);

        btnClose.setBackground(new java.awt.Color(0, 102, 255));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.setRound(5);
        btnClose.setSizeIcon(30.0F);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        btnVolverLibroDiario.setBackground(new java.awt.Color(102, 102, 102));
        btnVolverLibroDiario.setText("Volver");
        btnVolverLibroDiario.setBackgroundHover(new java.awt.Color(121, 121, 121));
        btnVolverLibroDiario.setFocusPainted(false);
        btnVolverLibroDiario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVolverLibroDiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverLibroDiario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnVolverLibroDiario.setRound(5);
        btnVolverLibroDiario.setSizeIcon(22.0F);
        btnVolverLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLibroDiarioActionPerformed(evt);
            }
        });

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setShapePanel(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tablaCuentaTransaccion.setForeground(new java.awt.Color(255, 255, 255));
        tablaCuentaTransaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cuenta", "Debe", "Haber", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentaTransaccion.setBackgoundHead(new java.awt.Color(240, 240, 240));
        tablaCuentaTransaccion.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tablaCuentaTransaccion.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tablaCuentaTransaccion.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tablaCuentaTransaccion.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tablaCuentaTransaccion.setColorSecondary(new java.awt.Color(240, 240, 240));
        tablaCuentaTransaccion.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tablaCuentaTransaccion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tablaCuentaTransaccion.setFontHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaCuentaTransaccion.setFontRowSelect(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tablaCuentaTransaccion.setForegroundHead(new java.awt.Color(51, 51, 51));
        tablaCuentaTransaccion.setGridColor(new java.awt.Color(255, 255, 255));
        tablaCuentaTransaccion.setModelSelection(null);
        tablaCuentaTransaccion.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane2.setViewportView(tablaCuentaTransaccion);
        if (tablaCuentaTransaccion.getColumnModel().getColumnCount() > 0) {
            tablaCuentaTransaccion.getColumnModel().getColumn(0).setResizable(false);
            tablaCuentaTransaccion.getColumnModel().getColumn(1).setResizable(false);
            tablaCuentaTransaccion.getColumnModel().getColumn(1).setPreferredWidth(300);
            tablaCuentaTransaccion.getColumnModel().getColumn(2).setResizable(false);
            tablaCuentaTransaccion.getColumnModel().getColumn(3).setResizable(false);
            tablaCuentaTransaccion.getColumnModel().getColumn(4).setResizable(false);
        }

        btnRegistrarTransaccion.setBackground(new java.awt.Color(27, 172, 27));
        btnRegistrarTransaccion.setText("Registrar transacción");
        btnRegistrarTransaccion.setBackgroundHover(new java.awt.Color(30, 191, 30));
        btnRegistrarTransaccion.setFocusPainted(false);
        btnRegistrarTransaccion.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnRegistrarTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarTransaccion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnRegistrarTransaccion.setRound(5);
        btnRegistrarTransaccion.setSizeIcon(22.0F);
        btnRegistrarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTransaccionActionPerformed(evt);
            }
        });

        labelDebe.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDebe.setText("0.00");

        labelHaber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelHaber.setText("0.00");

        inputFecha.setBackground(new java.awt.Color(102, 102, 102));
        inputFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputFecha.setFormatDate("dd/MM/yyyy");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Código");

        inputConcepto.setForeground(new java.awt.Color(51, 51, 51));
        inputConcepto.setBorderColor(new java.awt.Color(102, 102, 102));
        inputConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputConcepto.setPhColor(new java.awt.Color(102, 102, 102));
        inputConcepto.setPlaceholder("Digite una descripción");
        inputConcepto.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descripción");

        btnBuscarCuentaPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarCuentaPartida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 170, 227)));
        btnBuscarCuentaPartida.setForeground(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setText("Buscar cuenta");
        btnBuscarCuentaPartida.setBackgroundHover(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setFocusPainted(false);
        btnBuscarCuentaPartida.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnBuscarCuentaPartida.setForegroundIcon(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setForegroundText(new java.awt.Color(0, 170, 227));
        btnBuscarCuentaPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCuentaPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarCuentaPartida.setRound(5);
        btnBuscarCuentaPartida.setSizeIcon(22.0F);
        btnBuscarCuentaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaPartidaActionPerformed(evt);
            }
        });

        inputCodigoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        inputCodigoCuenta.setBorderColor(new java.awt.Color(102, 102, 102));
        inputCodigoCuenta.setEnabled(false);
        inputCodigoCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputCodigoCuenta.setPhColor(new java.awt.Color(102, 102, 102));
        inputCodigoCuenta.setPlaceholder("-");
        inputCodigoCuenta.setSelectionColor(new java.awt.Color(204, 204, 204));

        inputNomCuenta.setForeground(new java.awt.Color(51, 51, 51));
        inputNomCuenta.setBorderColor(new java.awt.Color(102, 102, 102));
        inputNomCuenta.setEnabled(false);
        inputNomCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNomCuenta.setPhColor(new java.awt.Color(102, 102, 102));
        inputNomCuenta.setPlaceholder("-");
        inputNomCuenta.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre de cuenta");

        inputSaldo.setForeground(new java.awt.Color(51, 51, 51));
        inputSaldo.setBorderColor(new java.awt.Color(102, 102, 102));
        inputSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputSaldo.setPhColor(new java.awt.Color(102, 102, 102));
        inputSaldo.setPlaceholder("0.00");
        inputSaldo.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Saldo ($)");

        selectTipoSaldo.setForeground(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Deudor", "Acreedor" }));
        selectTipoSaldo.setColorArrow(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setColorBorde(new java.awt.Color(102, 102, 102));
        selectTipoSaldo.setColorFondo(new java.awt.Color(255, 255, 255));
        selectTipoSaldo.setColorListaItemsTXT(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setColorSeleccion(new java.awt.Color(204, 204, 204));
        selectTipoSaldo.setColorSeleccionTXT(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setConBorde(true);
        selectTipoSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tipo de saldo");

        btnAgregarCuentaPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCuentaPartida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 172, 27)));
        btnAgregarCuentaPartida.setForeground(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setText("Agregar cuenta");
        btnAgregarCuentaPartida.setBackgroundHover(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setFocusPainted(false);
        btnAgregarCuentaPartida.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAgregarCuentaPartida.setForegroundIcon(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setForegroundText(new java.awt.Color(27, 172, 27));
        btnAgregarCuentaPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarCuentaPartida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAgregarCuentaPartida.setRound(5);
        btnAgregarCuentaPartida.setSizeIcon(22.0F);
        btnAgregarCuentaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(332, 489, Short.MAX_VALUE))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(selectTipoSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelHaber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(inputConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(btnBuscarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNomCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNomCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTipoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCuentaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDebe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHaber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("N° de Partida: 1");

        btnReportePartidas.setBackground(new java.awt.Color(249, 158, 9));
        btnReportePartidas.setText("Reporte de partidas");
        btnReportePartidas.setBackgroundHover(new java.awt.Color(249, 180, 66));
        btnReportePartidas.setFocusPainted(false);
        btnReportePartidas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnReportePartidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportePartidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER);
        btnReportePartidas.setRound(5);
        btnReportePartidas.setSizeIcon(22.0F);
        btnReportePartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePartidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(btnVolverLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportePartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolverLibroDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportePartidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCuentaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaPartidaActionPerformed

    }//GEN-LAST:event_btnAgregarCuentaPartidaActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        RSUtilities.setClosed();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnVolverLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLibroDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverLibroDiarioActionPerformed

    private void btnBuscarCuentaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCuentaPartidaActionPerformed

    private void btnRegistrarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTransaccionActionPerformed

    }//GEN-LAST:event_btnRegistrarTransaccionActionPerformed

    private void btnReportePartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePartidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePartidasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonIcon_new btnAgregarCuentaPartida;
    public newscomponents.RSButtonIcon_new btnBuscarCuentaPartida;
    private RSMaterialComponent.RSButtonIconOne btnClose;
    public newscomponents.RSButtonIcon_new btnRegistrarTransaccion;
    public newscomponents.RSButtonIcon_new btnReportePartidas;
    public newscomponents.RSButtonIcon_new btnVolverLibroDiario;
    public RSMaterialComponent.RSTextFieldOne inputCodigoCuenta;
    private RSMaterialComponent.RSTextFieldOne inputConcepto;
    private newscomponents.RSDateChooserModern inputFecha;
    public RSMaterialComponent.RSTextFieldOne inputNomCuenta;
    public RSMaterialComponent.RSTextFieldOne inputSaldo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelDebe;
    public javax.swing.JLabel labelHaber;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    public RSMaterialComponent.RSComboBox selectTipoSaldo;
    public RSMaterialComponent.RSTableMetro tablaCuentaTransaccion;
    // End of variables declaration//GEN-END:variables
}
