package vista.modulos;

import controlador.Controlador;

public class VistaHabitacion extends javax.swing.JPanel {

    public VistaHabitacion() {
        initComponents();
        btnNuevaHab.setActionCommand("NuevaHabitacion");
        btnReporteTotal.setActionCommand("ReporteHab");
    }
    
    public void setControlador(Controlador control){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        habPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfDir = new javax.swing.JTextField();
        tfTel = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHabitaciones = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnReporteTotal = new newscomponents.RSButtonIcon_new();
        btnNuevaHab = new newscomponents.RSButtonIcon_new();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        habPanel.setBackground(new java.awt.Color(255, 255, 255));
        habPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        habPanel.setAutoscrolls(true);
        habPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DIRECCIÓN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NOMBRE DEL HOTEL: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel4, gridBagConstraints);

        tfNom.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        tfNom.setCaretColor(new java.awt.Color(51, 51, 51));
        tfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomActionPerformed(evt);
            }
        });
        tfNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(tfNom, gridBagConstraints);

        tfDir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        tfDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDirActionPerformed(evt);
            }
        });
        tfDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDirKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(tfDir, gridBagConstraints);

        tfTel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        try {
            tfTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(tfTel, gridBagConstraints);

        habPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setOpaque(false);

        tablaHabitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tablaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Código", "Cuentas", "Folio", "Parcial", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHabitaciones.setAltoHead(30);
        tablaHabitaciones.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tablaHabitaciones.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tablaHabitaciones.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tablaHabitaciones.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tablaHabitaciones.setGridColor(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setGrosorBordeFilas(0);
        tablaHabitaciones.setGrosorBordeHead(0);
        tablaHabitaciones.setMultipleSeleccion(false);
        tablaHabitaciones.setRowHeight(40);
        tablaHabitaciones.getTableHeader().setResizingAllowed(false);
        tablaHabitaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaHabitaciones);
        if (tablaHabitaciones.getColumnModel().getColumnCount() > 0) {
            tablaHabitaciones.getColumnModel().getColumn(5).setPreferredWidth(10);
            tablaHabitaciones.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        habPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(habPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Libro diario / Registro de Partidas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        btnReporteTotal.setBackground(new java.awt.Color(102, 102, 255));
        btnReporteTotal.setText("Listado de partidas");
        btnReporteTotal.setBackgroundHover(new java.awt.Color(102, 102, 255));
        btnReporteTotal.setFocusPainted(false);
        btnReporteTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteTotal.setHideActionText(true);
        btnReporteTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReporteTotal.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIST);
        btnReporteTotal.setSizeIcon(22.0F);
        btnReporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(btnReporteTotal, gridBagConstraints);

        btnNuevaHab.setBackground(new java.awt.Color(61, 137, 248));
        btnNuevaHab.setText("Registrar partida");
        btnNuevaHab.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnNuevaHab.setFocusPainted(false);
        btnNuevaHab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevaHab.setHideActionText(true);
        btnNuevaHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNuevaHab.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnNuevaHab.setSizeIcon(22.0F);
        btnNuevaHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHabActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(btnNuevaHab, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTotalActionPerformed

    }//GEN-LAST:event_btnReporteTotalActionPerformed

    private void btnNuevaHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaHabActionPerformed

    private void tfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomActionPerformed

    private void tfNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomKeyTyped
        char val = evt.getKeyChar();
        if((val<'a' || val>'z') && (val < 'A' || val > 'Z') && (val < ' ')) evt.consume();
    }//GEN-LAST:event_tfNomKeyTyped

    private void tfDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDirActionPerformed

    private void tfDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDirKeyTyped
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonIcon_new btnNuevaHab;
    public newscomponents.RSButtonIcon_new btnReporteTotal;
    public javax.swing.JPanel habPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public rojerusan.RSTableMetro tablaHabitaciones;
    public javax.swing.JTextField tfDir;
    public javax.swing.JTextField tfNom;
    public javax.swing.JFormattedTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
