package vista.modulos;

import controlador.Controlador;
import ds.desktop.notify.DesktopNotify;
import ds.desktop.notify.NotifyTheme;
import utilidades.TextPrompt;

public class VistaLibroDiario extends javax.swing.JPanel {

    public VistaLibroDiario() {
        initComponents();
        
        /* Nombre de botones para identificarlos en el controlador */
        this.btnBuscarCuenta.setActionCommand("libroDiario_buscarCuenta");
        
        /* Insertar placeholder a los TextField */
        new TextPrompt("0.00", this.inputMonto);
        new TextPrompt("Ingrese el concepto de la transacción", this.inputConcepto);
    }
    
    public void setControlador(Controlador control){
        this.btnBuscarCuenta.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnReporteTotal = new newscomponents.RSButtonIcon_new();
        btnNuevaHab1 = new newscomponents.RSButtonIcon_new();
        bodyPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputMonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelNomCuenta = new javax.swing.JLabel();
        btnAgregarCuenta = new newscomponents.RSButtonIcon_new();
        labelCodCuenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNPartida = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputConcepto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnBuscarCuenta = new newscomponents.RSButtonIcon_new();
        jLabel14 = new javax.swing.JLabel();
        inputFecha = new newscomponents.RSDateChooser();
        selectTipoSaldo = new RSMaterialComponent.RSComboBox();
        tablaPanel = new javax.swing.JScrollPane();
        tablaDetallePartida = new rojerusan.RSTableMetro();
        footerPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelTotalDebe = new javax.swing.JLabel();
        labelTotalHaber = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        headPanel.setOpaque(false);
        headPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Libro diario / Registro de Partidas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        headPanel.add(jLabel3, gridBagConstraints);

        btnReporteTotal.setBackground(new java.awt.Color(102, 102, 255));
        btnReporteTotal.setText("Listado de partidas");
        btnReporteTotal.setBackgroundHover(new java.awt.Color(102, 102, 255));
        btnReporteTotal.setFocusPainted(false);
        btnReporteTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteTotal.setHideActionText(true);
        btnReporteTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReporteTotal.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIST);
        btnReporteTotal.setSizeIcon(22.0F);
        btnReporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        headPanel.add(btnReporteTotal, gridBagConstraints);

        btnNuevaHab1.setBackground(new java.awt.Color(61, 137, 248));
        btnNuevaHab1.setText("Registrar partida");
        btnNuevaHab1.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnNuevaHab1.setFocusPainted(false);
        btnNuevaHab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevaHab1.setHideActionText(true);
        btnNuevaHab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNuevaHab1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnNuevaHab1.setSizeIcon(22.0F);
        btnNuevaHab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHab1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        headPanel.add(btnNuevaHab1, gridBagConstraints);

        add(headPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        bodyPanel.setAutoscrolls(true);
        bodyPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 14, 0, 14, 0};
        jPanel2Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva partida");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Cuenta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel8, gridBagConstraints);

        inputMonto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        inputMonto.setCaretColor(new java.awt.Color(51, 51, 51));
        inputMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMontoActionPerformed(evt);
            }
        });
        inputMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputMontoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 0);
        jPanel2.add(inputMonto, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Tipo de saldo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        labelNomCuenta.setText("-");
        labelNomCuenta.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(labelNomCuenta, gridBagConstraints);

        btnAgregarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 170, 114), 1, true));
        btnAgregarCuenta.setForeground(new java.awt.Color(61, 137, 248));
        btnAgregarCuenta.setText("Agregar cuenta");
        btnAgregarCuenta.setBackgroundHover(new java.awt.Color(90, 170, 114));
        btnAgregarCuenta.setFocusPainted(false);
        btnAgregarCuenta.setFocusable(false);
        btnAgregarCuenta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAgregarCuenta.setForegroundIcon(new java.awt.Color(90, 170, 114));
        btnAgregarCuenta.setForegroundText(new java.awt.Color(90, 170, 114));
        btnAgregarCuenta.setHideActionText(true);
        btnAgregarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarCuenta.setIconTextGap(5);
        btnAgregarCuenta.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnAgregarCuenta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAgregarCuenta.setPreferredSize(new java.awt.Dimension(200, 35));
        btnAgregarCuenta.setSizeIcon(20.0F);
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 15);
        jPanel2.add(btnAgregarCuenta, gridBagConstraints);

        labelCodCuenta.setText("-");
        labelCodCuenta.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(labelCodCuenta, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabel11, gridBagConstraints);

        labelNPartida.setText("1");
        labelNPartida.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(labelNPartida, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("N° de partida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(jLabel12, gridBagConstraints);

        inputConcepto.setToolTipText("");
        inputConcepto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        inputConcepto.setCaretColor(new java.awt.Color(51, 51, 51));
        inputConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConceptoActionPerformed(evt);
            }
        });
        inputConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputConceptoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel2.add(inputConcepto, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Concepto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel2.add(jLabel13, gridBagConstraints);

        btnBuscarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 137, 248), 1, true));
        btnBuscarCuenta.setForeground(new java.awt.Color(61, 137, 248));
        btnBuscarCuenta.setText("Buscar cuenta");
        btnBuscarCuenta.setActionCommand("libroDiario_buscarCuenta");
        btnBuscarCuenta.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnBuscarCuenta.setFocusPainted(false);
        btnBuscarCuenta.setFocusable(false);
        btnBuscarCuenta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBuscarCuenta.setForegroundIcon(new java.awt.Color(61, 137, 248));
        btnBuscarCuenta.setForegroundText(new java.awt.Color(61, 137, 248));
        btnBuscarCuenta.setHideActionText(true);
        btnBuscarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCuenta.setIconTextGap(5);
        btnBuscarCuenta.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarCuenta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscarCuenta.setPreferredSize(new java.awt.Dimension(200, 35));
        btnBuscarCuenta.setSizeIcon(20.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnBuscarCuenta, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Monto ($)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabel14, gridBagConstraints);

        inputFecha.setBackground(new java.awt.Color(255, 255, 255));
        inputFecha.setForeground(new java.awt.Color(51, 51, 51));
        inputFecha.setAlignmentX(0.0F);
        inputFecha.setAlignmentY(0.0F);
        inputFecha.setBgColor(new java.awt.Color(204, 204, 204));
        inputFecha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inputFecha.setFormatDate("dd/MM/yyyy");
        inputFecha.setPreferredSize(new java.awt.Dimension(290, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(inputFecha, gridBagConstraints);

        selectTipoSaldo.setForeground(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Debe", "Haber" }));
        selectTipoSaldo.setColorArrow(new java.awt.Color(102, 102, 102));
        selectTipoSaldo.setColorBorde(new java.awt.Color(204, 204, 204));
        selectTipoSaldo.setColorFondo(new java.awt.Color(255, 255, 255));
        selectTipoSaldo.setColorSeleccion(new java.awt.Color(204, 204, 204));
        selectTipoSaldo.setColorSeleccionTXT(new java.awt.Color(51, 51, 51));
        selectTipoSaldo.setConBorde(true);
        selectTipoSaldo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel2.add(selectTipoSaldo, gridBagConstraints);

        headerPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        bodyPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        tablaPanel.setBackground(new java.awt.Color(255, 255, 255));
        tablaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablaPanel.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablaPanel.setOpaque(false);

        tablaDetallePartida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tablaDetallePartida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cuentas", "Folio", "Parcial", "Debe", "Haber", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetallePartida.setAltoHead(30);
        tablaDetallePartida.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tablaDetallePartida.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaDetallePartida.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaDetallePartida.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tablaDetallePartida.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaDetallePartida.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaDetallePartida.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tablaDetallePartida.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaDetallePartida.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaDetallePartida.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaDetallePartida.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaDetallePartida.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tablaDetallePartida.setGridColor(new java.awt.Color(255, 255, 255));
        tablaDetallePartida.setGrosorBordeFilas(0);
        tablaDetallePartida.setGrosorBordeHead(0);
        tablaDetallePartida.setMultipleSeleccion(false);
        tablaDetallePartida.setRowHeight(40);
        tablaDetallePartida.getTableHeader().setResizingAllowed(false);
        tablaDetallePartida.getTableHeader().setReorderingAllowed(false);
        tablaPanel.setViewportView(tablaDetallePartida);
        if (tablaDetallePartida.getColumnModel().getColumnCount() > 0) {
            tablaDetallePartida.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        bodyPanel.add(tablaPanel, java.awt.BorderLayout.CENTER);

        footerPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 10);
        jPanel3.add(jLabel10, gridBagConstraints);

        labelTotalDebe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalDebe.setForeground(new java.awt.Color(51, 51, 51));
        labelTotalDebe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalDebe.setText("Total debe: $0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 10);
        jPanel3.add(labelTotalDebe, gridBagConstraints);

        labelTotalHaber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalHaber.setForeground(new java.awt.Color(51, 51, 51));
        labelTotalHaber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalHaber.setText("Total haber: $0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 10);
        jPanel3.add(labelTotalHaber, gridBagConstraints);

        footerPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        bodyPanel.add(footerPanel, java.awt.BorderLayout.PAGE_END);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTotalActionPerformed

    }//GEN-LAST:event_btnReporteTotalActionPerformed

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    private void inputMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoActionPerformed

    private void inputMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMontoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoKeyTyped

    private void btnNuevaHab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHab1ActionPerformed
                
        if(!this.inputConcepto.getText().isEmpty() 
                && !this.inputMonto.getText().isEmpty() 
                && this.labelCodCuenta.getText().length() > 1
                && this.labelNomCuenta.getText().length() > 1
                && this.selectTipoSaldo.getSelectedIndex() > 0){
            
        }else{
            DesktopNotify.setDefaultTheme(NotifyTheme.Red);
            DesktopNotify.showDesktopMessage(
                    "Campos vacíos", 
                    "Debe completar todos los campos", 
                    DesktopNotify.ERROR, 
                    10000
            );
        }
    }//GEN-LAST:event_btnNuevaHab1ActionPerformed

    private void inputConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConceptoActionPerformed

    private void inputConceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputConceptoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConceptoKeyTyped
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bodyPanel;
    public newscomponents.RSButtonIcon_new btnAgregarCuenta;
    public newscomponents.RSButtonIcon_new btnBuscarCuenta;
    public newscomponents.RSButtonIcon_new btnNuevaHab1;
    public newscomponents.RSButtonIcon_new btnReporteTotal;
    private javax.swing.JPanel footerPanel;
    public javax.swing.JPanel headPanel;
    public javax.swing.JPanel headerPanel;
    public javax.swing.JTextField inputConcepto;
    private newscomponents.RSDateChooser inputFecha;
    public javax.swing.JTextField inputMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel labelCodCuenta;
    private javax.swing.JLabel labelNPartida;
    public javax.swing.JLabel labelNomCuenta;
    private javax.swing.JLabel labelTotalDebe;
    private javax.swing.JLabel labelTotalHaber;
    private RSMaterialComponent.RSComboBox selectTipoSaldo;
    public rojerusan.RSTableMetro tablaDetallePartida;
    private javax.swing.JScrollPane tablaPanel;
    // End of variables declaration//GEN-END:variables
}
